apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: myapp-devel
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2 # indica al controlador que ejecute 2 pods
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: fizzbuzz
        image: iraitz/fizzbuzz:1.0
        ports:
        - containerPort: 8000